INSERT INTO public.products (product_name, price_pkr, description, category, tags, material, stock_quantity, product_slug, main_image_url) VALUES
('Crochet Cherry Keychain', 400, 'A sweet pair of hand-crocheted cherries with a tiny leaf — the cutest little charm to bloom on your keys or bag. Each one is made stitch by stitch with love.', 'Keychains', ARRAY['cherry','fruit','cute','gift'], '100% soft cotton yarn with metal keyring', 10, 'cherry-keychain', '/products/cherry-keychain.jpg'),
('Crochet Sunflower Keychain', 350, 'A little ray of sunshine — this handmade sunflower keychain brings warmth and cheer wherever it goes. A thoughtful pick-me-up gift.', 'Keychains', ARRAY['sunflower','floral','yellow','gift'], '100% soft cotton yarn with metal keyring', 10, 'sunflower-keychain', '/products/sunflower-keychain.jpg'),
('Crochet Octopus Keychain', 400, 'An adorable little octopus with wiggly legs and shy eyes. Soft, squishy and endlessly huggable — a charming companion for your everyday carry.', 'Keychains', ARRAY['octopus','plush','cute','animal'], '100% soft cotton yarn with metal keyring', 10, 'octopus-keychain', '/products/octopus-keychain.jpg'),
('Crochet Bow Keychain', 300, 'A dainty little bow crocheted in dusty pink — soft, coquette and perfectly sweet. Tie a little charm onto anything you love.', 'Keychains', ARRAY['bow','coquette','pink','gift'], '100% soft cotton yarn with metal keyring', 10, 'bow-keychain', '/products/bow-keychain.jpg'),
('Crochet Rose Keychain', 350, 'A blooming rose that never wilts — hand-crocheted petals with a soft sage leaf. A romantic little keepsake to gift or keep.', 'Keychains', ARRAY['rose','floral','romantic','gift'], '100% soft cotton yarn with metal keyring', 10, 'rose-keychain', '/products/rose-keychain.jpg'),
('Crochet Floral Headband', 600, 'A cozy handmade headband adorned with tiny pastel blooms and sage leaves. Soft, stretchy and full of charm — wearable joy for everyday.', 'Wearables', ARRAY['headband','floral','wearable','accessory'], '100% soft cotton yarn, stretchy fit', 10, 'floral-headband', '/products/floral-headband.jpg');

INSERT INTO public.product_images (product_id, image_url, image_order)
SELECT id, main_image_url, 0 FROM public.products;